import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "mdsreact/styles/home.module.css";
import { Grid, Box, Container, Skeleton, Typography } from "@mui/material";
import LeftSidebar from "mdsreact/components/login/left-sidebar";
import Layout from "mdsreact/components/layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>MDS Demo</title>
        <meta
          name="description"
          content="Generated by create next app for MDS Demo"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container className={styles.main}> 
        <LeftSidebar />
        <Grid item xs={9} display={{ xs: "none", lg: "block" }}>
          <Container className={styles.container}>
            {/* Add Sliding Images Component */}
          </Container>
        </Grid>
      </Grid>
    </Layout>
  );
}
