import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from 'mdsreact/styles/Home.module.css'
import { Box, Container, Skeleton, Typography } from '@mui/material'
import Login from 'mdsreact/components/Navigation/LeftNavBar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>MDS Demo</title>
        <meta name="description" content="Generated by create next app for MDS Demo" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <main className={styles.main}>
        <Login/>
        <Container className={styles.container}>
          
                {/* Add Sliding Images Component */}

        </Container>
      </main>
    </>
  )
}
